services:
  - type: web
    name: presence-insa
    env: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
